### PR TITLE
Fix className(Binding)s

### LINKED ISSUE #137: Can't add property 0, object is not extensible
Trying to throw together a quick form with ember-form-for 2.0.0-alpha.13 and hitting a snag, probably because I'm on the bleeding edge!

```
Ember      : 2.11.0-beta.2
Ember Data : 2.11.0-beta.1
jQuery     : 3.1.1
```

Model:

```javascript
import DS from 'ember-data';

export default DS.Model.extend({
  displayName: DS.attr(),
  realName: DS.attr(),
  email: DS.attr(),

  comments: DS.hasMany(),
  posts: DS.hasMany()
});
```

Route:

```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.get('store').createRecord('author');
  }
});
```

Template:

```hbs
{{#form-for model as |f|}}
  {{f.text-field 'email' required=true}}
  {{f.text-field 'realName'}}
  {{f.text-field 'displayName'}}

  {{f.submit 'Sign up!'}}
{{/form-for}}
```

Error:

```
Uncaught TypeError: Can't add property 0, object is not extensible
    at Array.push (<anonymous>)
    at Class.init (form-field.js:57)
    at Class.superWrapper [as init] (ember.debug.js:39737)
    at new Class (ember.debug.js:35431)
    at Function._ClassMixinProps.create (ember.debug.js:35619)
    at CurlyComponentManager.create (ember.debug.js:12102)
    at OpenComponentOpcode.evaluate (ember.debug.js:46969)
    at VM.execute (ember.debug.js:53544)
    at Object.render (ember.debug.js:53118)
    at RootState.render (ember.debug.js:11389)
```

The line in form-field.js is:

```javascript
get(this, 'classNameBindings').push('hasErrors:' + get(this, 'config.fieldHasErrorClasses'));
```

### PR DESCRIPTION
**Pull request by martndemus**
Fixes #137

### CODE REVIEW

**Comment by martndemus** [comment]
Failure on CI was unrelated.

File: addon/components/form-field.js [hunk 1]
```diff
@@ -55,10 +55,11 @@ const FormFieldComponent = Component.extend({
     this._super(...arguments);
 
     let fieldClasses = get(this, 'config.fieldClasses');
-    let classNames = get(this, 'classNames');
-    set(this, 'classNames', (classNames || []).concat(fieldClasses));
 
-    get(this, 'classNameBindings').push(`hasErrors:${get(this, 'config.fieldHasErrorClasses')}`);
+    this.classNames = (this.classNames.slice() || []).concat(fieldClasses);
```
Comment (rwjblue) [inline addon/components/form-field.js]: this.classNames will always be defined. I think a simpler way to say what you need here is something like:

    this.classNames = this.classNames.concat(fieldClasses);

Comment (martndemus) [inline addon/components/form-field.js]: Ah sure, I just kept things as they were.
